package test.problem_java;

import java.util.Date;
import java.util.List;
import java.text.SimpleDateFormat;
import javax.swing.*;
import java.io.*;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;


public class MainFrame extends javax.swing.JFrame {
    DefaultListModel list = new DefaultListModel();
    File file = new File("");
    SimpleDateFormat sdform = new SimpleDateFormat("yyyy-MM-dd");
    Invoice inv = new Invoice();
    Payment p = new Payment();
    PaymentRequest pr = new PaymentRequest();;
    BufferedWriter save;
    BufferedReader open;
    List<String> bigdata = new ArrayList<String>();
    Available av = new Available();
    String title = null;

    public MainFrame() {
        initComponents();
        
        jList1.setModel(list);
        jDialog1.setBounds(0,0,300,300);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        ok = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jFileChooser1 = new javax.swing.JFileChooser();
        invoice1 = new javax.swing.JButton();
        payment = new javax.swing.JButton();
        payment_request1 = new javax.swing.JButton();
        save1 = new javax.swing.JButton();
        load1 = new javax.swing.JButton();
        view1 = new javax.swing.JButton();
        exit1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();

        ok.setText("OK");
        ok.setActionCommand("ok");
        ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialog1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ok)
                .addContainerGap())
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ok)
                .addGap(6, 6, 6))
        );

        ok.getAccessibleContext().setAccessibleName("ok");

        jFileChooser1.setDialogType(javax.swing.JFileChooser.SAVE_DIALOG);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        invoice1.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        invoice1.setText("Накладная");
        invoice1.setPreferredSize(new java.awt.Dimension(105, 25));
        invoice1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                invoice1ActionPerformed(evt);
            }
        });

        payment.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        payment.setText("Платежка");
        payment.setPreferredSize(new java.awt.Dimension(105, 25));
        payment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paymentActionPerformed(evt);
            }
        });

        payment_request1.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        payment_request1.setText("Заявка на оплату");
        payment_request1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payment_request1ActionPerformed(evt);
            }
        });

        save1.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        save1.setText("Сохранить");
        save1.setPreferredSize(new java.awt.Dimension(105, 25));
        save1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save1ActionPerformed(evt);
            }
        });

        load1.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        load1.setText("Загрузить");
        load1.setPreferredSize(new java.awt.Dimension(105, 25));
        load1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                load1ActionPerformed(evt);
            }
        });

        view1.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        view1.setText("Просмотр");
        view1.setPreferredSize(new java.awt.Dimension(105, 25));
        view1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view1ActionPerformed(evt);
            }
        });

        exit1.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        exit1.setText("Выход");
        exit1.setPreferredSize(new java.awt.Dimension(105, 25));
        exit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exit1ActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(jList1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(exit1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(view1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(load1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(save1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(payment_request1)
                    .addComponent(payment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(invoice1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(invoice1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(payment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(payment_request1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                        .addComponent(save1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(load1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(view1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(exit1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(14, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void invoice1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_invoice1ActionPerformed
        av.set("add"); //Определение выборки "Добавление нового док-та" для кнопки "ок"
        inv.setData(new Date());
        jDialog1.setVisible(true);
        jDialog1.setTitle(invoice1.getText());
        String s = String.format("Номер: %s\nДата: %s\nПользователь: %s\nСумма: %f\nВалюта: %s\nКурс Валюты: %f\nТовар: %s\nКоличество: %f", inv.getNum(), sdform.format(inv.getData()), inv.getUser(), inv.getSum(), inv.getValue(), inv.getcValue(), inv.getItem(), inv.getCount());
        jTextArea1.setText(s);
        
    }//GEN-LAST:event_invoice1ActionPerformed

    private void view1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view1ActionPerformed
        av.set("view"); //Просмотр/изменение сущ-го документа
        if(!jList1.isSelectionEmpty()) {
            jDialog1.setVisible(true);
            int a = jList1.getSelectedValue().indexOf("2");//Определение типа документа(платежка,накладная или заявка на оплату)
            jDialog1.setTitle(jList1.getSelectedValue().substring(0, a-3));//Извлечение слова из заголовка
            jTextArea1.setText(bigdata.get(jList1.getSelectedIndex()));
        }
    }//GEN-LAST:event_view1ActionPerformed

    private void exit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exit1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exit1ActionPerformed

    private void okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okActionPerformed
        if(av.get() == "add") {
        bigdata.add(jTextArea1.getText());//Добавление док-та в список данных
        Title(jTextArea1.getText());
        list.addElement(title);//Добавление в лист док/та с заголовком title
        }
        else if(av.get() == "view") {
            bigdata.set(jList1.getSelectedIndex(), jTextArea1.getText());
        }
        jDialog1.setVisible(false);
    }//GEN-LAST:event_okActionPerformed

    private void paymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paymentActionPerformed
        av.set("add");
        p.setData(new Date());
        jDialog1.setVisible(true);
        jDialog1.setTitle(payment.getText());
        String s = String.format("Номер: %s\nДата: %s\nПользователь: %s\nСумма: %f\nСотрудник: %s", p.getNum(), sdform.format(p.getData()),p.getUser(), p.getSum(), p.getWorker());
        jTextArea1.setText(s);
           
    }//GEN-LAST:event_paymentActionPerformed

    private void payment_request1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payment_request1ActionPerformed
        av.set("add");
        pr.setData(new Date());
        jDialog1.setTitle(payment_request1.getText());
        jDialog1.setVisible(true);
        String s = String.format("Номер: %s\nДата: %s\nПользователь: %s\nКонтрагент: %s\nСумма: %f\nВалюта: %s\nКурс Валюты: %f\nКомиссия: %f", pr.getNum(), sdform.format(pr.getData()),pr.getUser(), pr.getContr(), pr.getSum(), pr.getValue(), pr.getcValue(), pr.getChange());
        jTextArea1.setText(s);
        
    }//GEN-LAST:event_payment_request1ActionPerformed

    private void save1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save1ActionPerformed
        if(!jList1.isSelectionEmpty())
            try {
                if(jFileChooser1.showSaveDialog(null) == JFileChooser.APPROVE_OPTION) {
                    save = new BufferedWriter(new FileWriter(jFileChooser1.getSelectedFile().getName()));
                    save.write(bigdata.get(jList1.getSelectedIndex()));
                    save.close();
                }
            } catch (IOException ex) {
                Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_save1ActionPerformed

    private void load1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_load1ActionPerformed
            try {
                if(jFileChooser1.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {
                    open = new BufferedReader(new FileReader(jFileChooser1.getSelectedFile().getName()));
                    String newFile = null;
                    StringBuilder sb = new StringBuilder();
                    String ls = System.getProperty("line.separator");
                    while((newFile = open.readLine()) != null) {
                        sb.append(newFile);
                        sb.append(ls);
                    }
                    sb.deleteCharAt(sb.length()-1);
                    bigdata.add(sb.toString());
                    Title(sb.toString());
                    list.addElement(title);
                    open.close();
                }  
        } catch (IOException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_load1ActionPerformed
    
    public void Title(String s) { //Определение типа(заголовка) документа(платежка,накладная или заявка на оплату)
        if(s.contains("Количество")) {
            title = String.format("%s от %s номер: %s", invoice1.getText(), sdform.format(new Date()), inv.getNum());
        } else if (s.contains("Сотрудник")) {
            title = String.format("%s от %s номер: %s", payment.getText(), sdform.format(new Date()), p.getNum());
        } else if (s.contains("Комиссия")) {
            title = String.format("%s от %s номер: %s", payment_request1.getText(), sdform.format(new Date()), pr.getNum());
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton exit1;
    private javax.swing.JButton invoice1;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton load1;
    private javax.swing.JButton ok;
    private javax.swing.JButton payment;
    private javax.swing.JButton payment_request1;
    private javax.swing.JButton save1;
    private javax.swing.JButton view1;
    // End of variables declaration//GEN-END:variables
}
